import { FormEvent, useMemo, useState } from "react";
import { ArrowDownUp, ArrowUpRight, BarChart3, Check, ChevronDown, CircleHelp, Clock3, Eye, Filter, Menu, Search, ShieldCheck, SlidersHorizontal, Star, X } from "lucide-react";

type Listing = { id: string; name: string; type: string; sector: string; price: number | null; priceLabel: string; lot: string; liquidity: string; updated: string; stage: string; description: string; metrics: string[]; };

const listings: Listing[] = [
  { id: "tata-capital", name: "Tata Capital", type: "Pre-IPO", sector: "Financial Services", price: 1100, priceLabel: "₹ 1,100", lot: "10 shares", liquidity: "Moderate", updated: "Today, 10:15 AM", stage: "IPO watch", description: "A Tata Group financial services business with a broad retail and institutional customer base.", metrics: ["Financial Services", "Pre-IPO", "Indicative range ₹1,050–₹1,150"] },
  { id: "hdfc-securities", name: "HDFC Securities", type: "Pre-IPO", sector: "Financial Services", price: 7800, priceLabel: "₹ 7,800", lot: "1 share", liquidity: "Moderate", updated: "Yesterday, 4:30 PM", stage: "Pre-IPO", description: "A full-service capital-markets platform serving investors across India.", metrics: ["Financial Services", "Pre-IPO", "Indicative price ₹7,800"] },
  { id: "studds", name: "Studds Accessories", type: "Unlisted", sector: "Consumer", price: 680, priceLabel: "₹ 680", lot: "50 shares", liquidity: "Limited", updated: "12 Sep 2026", stage: "Unlisted", description: "A helmet and accessories manufacturer with a growing consumer footprint.", metrics: ["Consumer", "Unlisted", "Minimum indicative order ₹34,000"] },
  { id: "bira-91", name: "Bira 91", type: "Unlisted", sector: "Food & Beverage", price: 250, priceLabel: "₹ 250", lot: "100 shares", liquidity: "Limited", updated: "10 Sep 2026", stage: "Unlisted", description: "An Indian craft beer brand operating across a growing network of markets.", metrics: ["Food & Beverage", "Unlisted", "Indicative price ₹250"] },
  { id: "msei", name: "MSEI", type: "Unlisted", sector: "Capital Markets", price: 3.8, priceLabel: "₹ 3.80", lot: "1,000 shares", liquidity: "Limited", updated: "09 Sep 2026", stage: "Unlisted", description: "A recognized stock exchange platform serving the Indian capital markets ecosystem.", metrics: ["Capital Markets", "Unlisted", "Indicative price ₹3.80"] },
  { id: "esop-desk", name: "ESOP Liquidity Desk", type: "ESOPs", sector: "Secondary transactions", price: null, priceLabel: "On request", lot: "Case-specific", liquidity: "Case-specific", updated: "By enquiry", stage: "Seller route", description: "A guided route for employees and early holders exploring secondary liquidity for eligible shares.", metrics: ["Secondary transactions", "ESOPs", "Specialist assessment required"] },
  { id: "nse-india", name: "NSE India", type: "Pre-IPO", sector: "Capital Markets", price: 1850, priceLabel: "₹ 1,850", lot: "10 shares", liquidity: "Moderate", updated: "08 Sep 2026", stage: "IPO watch", description: "India's leading exchange platform and a widely followed private-market name.", metrics: ["Capital Markets", "Pre-IPO", "Indicative price ₹1,850"] },
  { id: "oyo", name: "OYO", type: "Unlisted", sector: "Consumer Internet", price: 85, priceLabel: "₹ 85", lot: "500 shares", liquidity: "Limited", updated: "05 Sep 2026", stage: "Unlisted", description: "A hospitality technology platform with a large network of operating properties.", metrics: ["Consumer Internet", "Unlisted", "Indicative order from ₹42,500"] },
];
const categories = ["All opportunities", "Pre-IPO", "Unlisted", "ESOPs"];
const sectors = ["All sectors", ...Array.from(new Set(listings.map((listing) => listing.sector)))];

function Logo() { return <a className="ww-logo" href="#top" aria-label="Wealth Wisdom India home"><span className="logo-mark"><i /><i /><i /><i /></span><span><strong>WEALTH</strong><em>WISDOM</em><small>INDIA</small></span></a>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [category, setCategory] = useState("All opportunities");
  const [query, setQuery] = useState("");
  const [sector, setSector] = useState("All sectors");
  const [sortBy, setSortBy] = useState("relevance");
  const [watchlist, setWatchlist] = useState<string[]>([]);
  const [compare, setCompare] = useState<string[]>([]);
  const [selected, setSelected] = useState<Listing | null>(null);
  const [enquiry, setEnquiry] = useState<Listing | null>(null);
  const [submitted, setSubmitted] = useState(false);
  const [helpOpen, setHelpOpen] = useState(false);

  const filtered = useMemo(() => {
    const result = listings.filter((item) => {
      const text = `${item.name} ${item.type} ${item.sector}`.toLowerCase();
      return (category === "All opportunities" || item.type === category) && (sector === "All sectors" || item.sector === sector) && text.includes(query.toLowerCase().trim());
    });
    if (sortBy === "name") result.sort((a, b) => a.name.localeCompare(b.name));
    if (sortBy === "price-low") result.sort((a, b) => (a.price ?? Infinity) - (b.price ?? Infinity));
    if (sortBy === "price-high") result.sort((a, b) => (b.price ?? -Infinity) - (a.price ?? -Infinity));
    return result;
  }, [category, query, sector, sortBy]);

  const toggleWatch = (id: string) => setWatchlist((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]);
  const toggleCompare = (id: string) => setCompare((items) => items.includes(id) ? items.filter((item) => item !== id) : items.length < 3 ? [...items, id] : items);
  const resetFilters = () => { setCategory("All opportunities"); setQuery(""); setSector("All sectors"); setSortBy("relevance"); };
  const submitEnquiry = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true); };

  return (
    <div className="ww-page" id="top">
      <div className="top-rail" aria-label="WWIPL market services"><div className="rail-inner"><div className="rail-set"><span>WWIPL / PRIVATE MARKET ACCESS</span><span>UNLISTED SHARES</span><span>PRE-IPO OPPORTUNITIES</span><span>ESOP LIQUIDITY</span><span>19+ YEARS OF MARKET EXPERIENCE</span></div><div className="rail-set" aria-hidden="true"><span>WWIPL / PRIVATE MARKET ACCESS</span><span>UNLISTED SHARES</span><span>PRE-IPO OPPORTUNITIES</span><span>ESOP LIQUIDITY</span><span>19+ YEARS OF MARKET EXPERIENCE</span></div></div></div>
      <header className="ww-header"><Logo /><nav className={menuOpen ? "nav-open" : ""}><a href="#market" onClick={() => setMenuOpen(false)}>Explore market</a><a href="#services" onClick={() => setMenuOpen(false)}>Services</a><a href="#process" onClick={() => setMenuOpen(false)}>How it works</a><a href="#research" onClick={() => setMenuOpen(false)}>Research</a><a className="header-cta" href="#market" onClick={() => setMenuOpen(false)}>Browse opportunities <ArrowUpRight size={14} /></a></nav><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></header>

      <main>
        <section className="command-hero">
          <div className="hero-grid-lines" /><div className="hero-chart"><svg viewBox="0 0 800 420" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#bcff2c" stopOpacity=".2" /><stop offset="1" stopColor="#bcff2c" stopOpacity="0" /></linearGradient></defs><path className="chart-fill" d="M0 370 L55 342 L90 355 L130 294 L172 305 L220 250 L265 279 L305 220 L346 239 L386 186 L430 215 L462 174 L505 190 L548 122 L590 143 L630 93 L671 112 L720 46 L800 15 L800 420 L0 420Z" /><path className="chart-path" d="M0 370 L55 342 L90 355 L130 294 L172 305 L220 250 L265 279 L305 220 L346 239 L386 186 L430 215 L462 174 L505 190 L548 122 L590 143 L630 93 L671 112 L720 46 L800 15" /></svg><div className="axis-labels"><span>2023</span><span>2024</span><span>2025</span><span>NOW</span></div></div><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" />
          <div className="hero-content"><div className="hero-eyebrow"><span className="pulse-dot" /> WEALTH WISDOM INDIA <span>PRIVATE MARKET ACCESS</span></div><h1>Buy &amp; sell<br /><em>unlisted</em><br />shares in India.</h1><p>Discover pre-IPO, unlisted and ESOP opportunities with transparent information and practical support from enquiry to settlement.</p><div className="hero-actions"><a className="primary-cta" href="#market">Explore current opportunities <ArrowUpRight size={16} /></a><a className="play-link" href="#process"><span>→</span> How buying works</a></div><div className="hero-proof"><span><strong>19+</strong> years in the market</span><span><strong>500+</strong> companies tracked</span><span><strong>4</strong> access routes</span></div></div>
          <div className="hero-market-card"><div className="hero-card-top"><span><i /> WWIPL MARKET DESK</span><small>DATA STATUS: CURATED</small></div><div className="hero-card-value">500+ <span>companies tracked</span></div><div className="hero-card-grid"><div><small>PRE-IPO</small><b>42</b></div><div><small>UNLISTED</small><b>391</b></div><div><small>ESOP / EXIT</small><b>67</b></div></div><a href="#market">Open the market directory <ArrowUpRight size={14} /></a></div>
          <div className="hero-feature-card"><span>FEATURED OPPORTUNITY</span><strong>Tata Capital</strong><small>Pre-IPO · Financial Services</small><div><b>₹ 1,100</b><em>Indicative price</em></div></div><div className="hero-side-label">PRE-IPO / UNLISTED / ESOPS</div><div className="hero-scroll">SCROLL TO EXPLORE <span>↓</span></div>
        </section>

        <section className="trust-strip"><div><ShieldCheck size={18} /><strong>Transparent by design</strong><span>Indicative prices, freshness and risk context at the point of decision.</span></div><div><BarChart3 size={18} /><strong>Research-led discovery</strong><span>Company information before you submit an enquiry.</span></div><div><Clock3 size={18} /><strong>Human support</strong><span>Clear next steps from enquiry through settlement.</span></div></section>

        <section className="thesis-section" id="services"><div className="section-wrap"><div className="section-kicker"><span>01</span> THE WWIPL DIFFERENCE</div><div className="thesis-grid"><h2>Private-market access<br /><em>without the guesswork.</em></h2><div className="thesis-copy"><p>We help you move from “what is this company?” to “what should I do next?” with a clearer directory, deeper context and a more accountable enquiry process.</p><a className="arrow-link" href="#process">See how the process works <ArrowUpRight size={16} /></a><div className="signal-line"><span>DISCOVER</span><b /><span>RESEARCH</span><b /><span>ENQUIRE</span></div></div></div></div></section>

        <section className="market-section" id="market"><div className="section-wrap"><div className="section-kicker"><span>02</span> WWIPL MARKET DIRECTORY</div><div className="market-title-row"><div><h2>Find the right<br /><em>opportunity.</em></h2><p>Search the public directory, compare opportunities, save a watchlist, and ask our team about the next step.</p></div><div className="market-title-actions"><span className="data-status"><i /> Demo data · connect live feed for production</span><button className="help-link" onClick={() => setHelpOpen(true)}><CircleHelp size={15} /> What does indicative mean?</button></div></div>
          <div className="market-workspace"><div className="market-tabs" role="tablist">{categories.map((item) => <button key={item} role="tab" aria-selected={category === item} className={category === item ? "active" : ""} onClick={() => setCategory(item)}>{item}</button>)}</div><div className="lookup-toolbar"><label className="lookup-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search company, type or sector" aria-label="Search company, type or sector" /></label><label><span>Sector</span><select value={sector} onChange={(event) => setSector(event.target.value)}>{sectors.map((item) => <option key={item}>{item}</option>)}</select></label><label><span>Sort</span><select value={sortBy} onChange={(event) => setSortBy(event.target.value)}><option value="relevance">Featured</option><option value="name">Company name</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select></label><button className="clear-lookup" onClick={resetFilters}>Reset</button></div><div className="lookup-summary"><strong>{filtered.length}</strong> opportunities shown <span>{watchlist.length} saved · {compare.length}/3 selected for compare</span></div>
            <div className="market-list"><div className="market-list-head"><span>Company / opportunity</span><span>Type</span><span>Sector</span><span>Indicative price</span><span>Liquidity</span><span>Updated</span><span /></div>{filtered.length > 0 ? filtered.map((item) => <div className="market-list-row" key={item.id}><span className="company-name"><b>{item.name.slice(0, 2).toUpperCase()}</b><strong>{item.name}</strong><small>{item.stage}</small></span><span className="type-chip">{item.type}</span><span>{item.sector}</span><span className="price-cell">{item.priceLabel}<small>per share / indicative</small></span><span>{item.liquidity}</span><span className="updated-cell">{item.updated}</span><span className="row-actions"><button onClick={() => toggleWatch(item.id)} className={watchlist.includes(item.id) ? "saved" : ""} aria-label={watchlist.includes(item.id) ? `Remove ${item.name} from watchlist` : `Save ${item.name} to watchlist`}><Eye size={15} /></button><button onClick={() => toggleCompare(item.id)} className={compare.includes(item.id) ? "saved" : ""} aria-label={`Compare ${item.name}`}><ArrowDownUp size={15} /></button><button onClick={() => setSelected(item)} aria-label={`View details for ${item.name}`}><ArrowUpRight size={15} /></button></span></div>) : <div className="lookup-empty"><strong>No matching opportunities</strong><span>Try another company, category or sector.</span><button onClick={resetFilters}>Reset directory</button></div>}</div><p className="market-disclaimer">Indicative prices are not executable quotes. Availability, pricing, lot size and transfer timelines can change. Unlisted investments are illiquid and higher-risk.</p></div>
        </div></section>

        {compare.length > 0 && <div className="compare-bar"><div><strong>{compare.length}/3 selected</strong><span>{compare.map((id) => listings.find((item) => item.id === id)?.name).join(" · ")}</span></div><button onClick={() => setCompare([])}>Clear</button><button className="compare-primary" onClick={() => setHelpOpen(true)}>Compare selected <ArrowUpRight size={14} /></button></div>}

        <section className="process-section" id="process"><div className="section-wrap"><div className="section-kicker pale"><span>03</span> FROM DISCOVERY TO SETTLEMENT</div><div className="process-grid"><div><h2>A clearer<br /><em>next step.</em></h2><p>Private-market transactions are unfamiliar for most investors. We make the process easier to understand before you commit.</p><a className="primary-cta" href="mailto:care@wwipl.com?subject=WWIPL process enquiry">Speak to a specialist <ArrowUpRight size={16} /></a></div><div className="process-steps"><div><span>01</span><div><h3>Discover</h3><p>Search the directory and shortlist opportunities by category, sector, price and liquidity.</p></div></div><div><span>02</span><div><h3>Understand</h3><p>Review company information, indicative context, risks, lot size and source freshness.</p></div></div><div><span>03</span><div><h3>Enquire</h3><p>Tell us what you want to buy or sell. We confirm availability, documentation and next steps.</p></div></div><div><span>04</span><div><h3>Settle</h3><p>Complete KYC and documentation, then follow the transaction through to demat transfer.</p></div></div></div></div></div></section>

        <section className="faq-section" id="research"><div className="section-wrap"><div className="section-kicker"><span>04</span> BEFORE YOU ENQUIRE</div><div className="faq-grid"><div><h2>The useful<br /><em>questions.</em></h2><p>Private-market investing has more moving parts than a listed stock order. We explain the ones that matter.</p></div><div className="faq-list"><details open><summary>What does “indicative price” mean? <ChevronDown size={16} /></summary><p>It is a current market indication, not a guaranteed executable quote. Final availability and price are confirmed during the enquiry process.</p></details><details><summary>How liquid are unlisted shares? <ChevronDown size={16} /></summary><p>Liquidity is generally lower than listed shares. Time to sell, buyer availability and price can vary by company and transaction.</p></details><details><summary>What information should I review? <ChevronDown size={16} /></summary><p>Review company fundamentals, ownership, events, documents, valuation context, transfer terms, fees, tax treatment and the risks of loss.</p></details></div></div></div></section>

        <section className="final-section"><div className="final-grid"><div className="final-copy"><div className="section-kicker pale"><span>05</span> START WITH A CONVERSATION</div><h2>Have a company<br /><em>in mind?</em></h2><p>Send us the name, quantity or goal. We will help you understand what is possible and what happens next.</p><a className="primary-cta" href="mailto:care@wwipl.com?subject=Private market enquiry">Send an enquiry <ArrowUpRight size={16} /></a></div><div className="final-data"><div className="data-title"><span>WWIPL / INVESTOR DESK</span><small>CARE@WWIPL.COM</small></div><div className="data-quote">Clear information.<br />Direct access.<br /><em>Better decisions.</em></div><div className="data-footer"><span>INDIA / PRIVATE MARKETS</span><a href="mailto:care@wwipl.com">CARE@WWIPL.COM ↗</a></div></div></div></section>
      </main>
      <footer className="ww-footer"><Logo /><span>© 2026 Wealth Wisdom India Pvt. Ltd.</span><div><a href="https://wwipl.com/privacy-policy">Privacy</a><a href="https://wwipl.com/term-n-condition">Terms</a><a href="https://www.linkedin.com/company/wealthwisdomindia2/">LinkedIn</a></div></footer>

      {selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><aside className="detail-drawer" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setSelected(null)} aria-label="Close detail"><X size={18} /></button><span className="drawer-kicker">{selected.type} · {selected.stage}</span><h2>{selected.name}</h2><p>{selected.description}</p><div className="detail-stat"><span>Indicative price</span><strong>{selected.priceLabel}</strong><small>Updated {selected.updated}</small></div><div className="detail-grid"><div><span>Sector</span><strong>{selected.sector}</strong></div><div><span>Lot size</span><strong>{selected.lot}</strong></div><div><span>Liquidity</span><strong>{selected.liquidity}</strong></div><div><span>Data state</span><strong>Indicative</strong></div></div><h3>What to review</h3><ul>{selected.metrics.map((metric) => <li key={metric}><Check size={14} />{metric}</li>)}</ul><p className="drawer-note">This is information for discussion, not investment advice or an executable offer.</p><button className="primary-cta full-cta" onClick={() => { setSelected(null); setEnquiry(selected); setSubmitted(false); }}>Enquire about {selected.name} <ArrowUpRight size={15} /></button></aside></div>}
      {enquiry && <div className="modal-backdrop" onClick={() => setEnquiry(null)}><aside className="enquiry-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setEnquiry(null)} aria-label="Close enquiry"><X size={18} /></button>{submitted ? <div className="success-state"><div className="success-icon"><Check size={22} /></div><h2>Enquiry received.</h2><p>We have recorded your interest in {enquiry.name}. A WWIPL specialist will contact you with availability, documentation and next steps.</p><span>Reference: WW-{enquiry.id.slice(0, 4).toUpperCase()}-2026</span><button className="primary-cta" onClick={() => setEnquiry(null)}>Close <ArrowUpRight size={15} /></button></div> : <><span className="drawer-kicker">PRIVATE MARKET ENQUIRY</span><h2>Ask about<br /><em>{enquiry.name}.</em></h2><p>Tell us what you are looking for. There is no obligation to transact.</p><form onSubmit={submitEnquiry}><label>Your name<input required placeholder="Full name" /></label><label>Mobile number<input required pattern="[0-9+ ]{8,}" placeholder="+91 00000 00000" /></label><label>What are you looking to do?<select defaultValue="Buy"><option>Buy shares</option><option>Sell shares</option><option>Understand ESOP liquidity</option><option>Request research</option></select></label><label>Message<textarea placeholder="Quantity, ticket size or question (optional)" rows={3} /></label><label className="consent"><input required type="checkbox" /> I agree to be contacted about this enquiry.</label><button className="primary-cta full-cta" type="submit">Submit enquiry <ArrowUpRight size={15} /></button></form></>}</aside></div>}
      {helpOpen && <div className="modal-backdrop" onClick={() => setHelpOpen(false)}><aside className="help-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setHelpOpen(false)} aria-label="Close help"><X size={18} /></button><span className="drawer-kicker">MARKET DIRECTORY GUIDE</span><h2>Indicative means<br /><em>context, not a quote.</em></h2><p>Prices shown in the directory are the latest available market indications for discussion. They are not guaranteed executable prices. Availability, lot size, documentation, transfer timelines and final terms are confirmed after enquiry.</p><div className="help-points"><div><ShieldCheck size={16} /><span><strong>Clear status</strong>Each row shows whether data is indicative, unavailable or case-specific.</span></div><div><Clock3 size={16} /><span><strong>Freshness</strong>Every listing carries an update time or explains why it is by enquiry.</span></div><div><CircleHelp size={16} /><span><strong>Human confirmation</strong>Our team confirms the next step before any transaction proceeds.</span></div></div><a className="primary-cta full-cta" href="mailto:care@wwipl.com?subject=How indicative pricing works">Ask a question <ArrowUpRight size={15} /></a></aside></div>}
    </div>
  );
}
